#pragma once

#include "raylib.h"

#define DECLARE_DEBUG_VAR(VAR_NAME) \
    bool Debug##VAR_NAME()
    
DECLARE_DEBUG_VAR(WindowBox);
DECLARE_DEBUG_VAR(GroupBox);
DECLARE_DEBUG_VAR(Line);
DECLARE_DEBUG_VAR(Panel);
DECLARE_DEBUG_VAR(TabBar);
DECLARE_DEBUG_VAR(ScrollPanel);

DECLARE_DEBUG_VAR(Label);
DECLARE_DEBUG_VAR(Button);
DECLARE_DEBUG_VAR(LabelButton);
DECLARE_DEBUG_VAR(Toggle);
DECLARE_DEBUG_VAR(ToggleGroup);
DECLARE_DEBUG_VAR(ToggleSlider);
DECLARE_DEBUG_VAR(CheckBox);
DECLARE_DEBUG_VAR(ComboBox);
DECLARE_DEBUG_VAR(DropdownBox);
DECLARE_DEBUG_VAR(Spinner);
DECLARE_DEBUG_VAR(ValueBox);
DECLARE_DEBUG_VAR(ValueBoxFloat);
DECLARE_DEBUG_VAR(TextBox);
DECLARE_DEBUG_VAR(Slider);
DECLARE_DEBUG_VAR(SliderBar);
DECLARE_DEBUG_VAR(ProgressBar);
DECLARE_DEBUG_VAR(DummyRec);
DECLARE_DEBUG_VAR(Grid);
DECLARE_DEBUG_VAR(StatusBar);

DECLARE_DEBUG_VAR(MessageBox);
DECLARE_DEBUG_VAR(TextInputBox);
DECLARE_DEBUG_VAR(ListView);
DECLARE_DEBUG_VAR(ListViewEx);
DECLARE_DEBUG_VAR(ColorPicker);
